apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: example
          image: image-ver
          command:
            - sleep
            - inf
          env:
            - name: USER_NAME
              value: update-via-replacement
            - name: USER_PASSWORD
              value: update-via-replacement
        - name: foobar
          image: docker.io/alpine:image-tag
          command:
            - sleep
            - inf
          env:
            - name: USER_NAME
              value: update-via-replacement
            - name: USER_PASSWORD
              value: update-via-replacement
