apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  envName: env1

resources:
  - ../../base

components:
  - ../../components/replace-username-password

configMapGenerator:
  - name: local
    literals:
      - image-ver=docker.io/alpine:prod

replacements:
- source: 
    kind: ConfigMap
    name: local
    fieldPath: data.image-ver
  targets:
  - select: 
      kind: Deployment
      name: example
    fieldPaths:
    - spec.template.spec.containers.[name=example].image
